baseurl = "https://ivalab.github.io/Controls/public/"
baseURL = "https://ivalab.github.io/Controls/public/"
title = "Controls Research"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
defaultContentLanguage = "en-us"
disqusShortname = ""
googleAnalytics = ""

[params]
  style = "sea"
  title = "IVALab:RoboSLAM"
  description = "Research efforts related to learning and adaptation in control."
  copyright = ""
  support = "Research supported in part by National Science Foundation.  Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation."
  sidebarAbout = [ "Research efforts related to learning and adaptation in control for robustness to modeling uncertainty and other unkown factors." ]


  [[params.grants]]
  grantee = "NSF"
  award = "1544857"
  url = "https://www.nsf.gov/awardsearch/showAward?AWD_ID=1544857&HistoricalAwards=false"

  [[params.grants]]
  grantee = "NSF"
  award = "0846750"
  url = "https://www.nsf.gov/awardsearch/showAward?AWD_ID=0846750&HistoricalAwards=false"

  [[params.navlinks]]
  name = "About"
  url = "about/"
  home = false

  [[params.navlinks]]
  name = "Robots"
  url  = "robots/"
  home = false

  [[params.navlinks]]
  name = "Research"
  url  = "research/"
  home = true

  [params.social]
  github  = "https://github.com/ivalab"
  github2  = "https://github.com/ivaROS"
